### PR TITLE
Typo fix in rust-lint-config.md

### PR DESCRIPTION
**Pull request by obi1kenobi**

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Another thing you might consider is adding `white-space: nowrap` CSS to short code blocks that contain `#` symbols. Browsers' line wrapping algorithm assumes it can wrap between the `#` and subsequent characters, so you often end up with annoyingly line-broken code blocks that look like this:
code block with line break between `#` and subsequent text

For my blog, I've defined a CSS class called `.nobr` that looks like this:
```css
.nobr {
    white-space: nowrap;
}
```
and then use it on one-line code elements at risk of having this problem (e.g. ones with `#` symbols) like so:
```markdown
something something <span class="nobr">`#[repr(transparent)]`</span>
```

**Comment by suaviloquence** [comment]
Thank you!

**Comment by obi1kenobi** [comment]
Of course, happy to help! I really liked your post btw! It was very thoughtful, sparked some good discussion, and as a result all three of us (you, me, and Ed) are on the same page with each other about the plan here.

Are you posting links to your posts on social media btw? I'd be happy to boost / repost / retweet them if so.

**Comment by suaviloquence** [comment]
> Are you posting links to your posts on social media btw? I'd be happy to boost / repost / retweet them if so.

I was thinking about making a mastodon or something for this, but i haven't yet. Thanks, and I'll let you know if I do.

**Pull request merged**
